#!/bin/sh
# shellcheck disable=SC2034

# Description: Event notification library
# URL:         http://www.monkey.org/~provos/libevent/
# Maintainer:  James Mills, prologic at shortcircuit dot net dot au

name=libevent
version=2.1.11
release=2
source="https://github.com/libevent/libevent/releases/download/release-$version-stable/$name-$version-stable.tar.gz"

build() {
  cd $name-$version-stable || exit 1

  ./configure \
    --prefix=/usr

  make -j "$(nproc)"

  make DESTDIR="$PKG" install
}
