#!/bin/sh

# This file is included by download.sh & build.sh

set -e

KERNEL_VERSION=5.6.3
SINIT_VERSION=1.0
MUSL_VERSION=1.2.0
FASM_VERSION=1.73.22
MAKE_VERSION=4.3
BUSYBOX_VERSION=snapshot
DROPBEAR_VERSION=2019.78
SYSLINUX_VERSION=6.03
RNGTOOLS_VERSION=5
IPTABLES_VERSION=1.8.2

NUM_JOBS="$(grep -c ^processor /proc/cpuinfo)"

export KERNEL_VERSION
export SINIT_VERSION
export MUSL_VERSION
export FASM_VERSION
export MAKE_VERSION
export BUSYBOX_VERSION
export DROPBEAR_VERSION
export SYSLINUX_VERSION
export RNGTOOLS_VERSION
export IPTABLES_VERSION

export NUM_JOBS
