#!/bin/sh
# shellcheck disable=SC2034

# Description: an out-of-tree version of getconf (normally provided by glibc)
# URL:         https://github.com/alpinelinux/aports
# Maintainer:  James Mills, prologic at shortcircuit dot net dot au

name="getconf"
version=1
release=1
source="$name.c"

build() {
  cd "$SRC" || exit 1

  $CC "$CFLAGS" -o $name $name.c

  install -D -m 755 $name "$PKG"/usr/bin/$name
}
