#!/bin/sh
# shellcheck disable=SC2034

# Description: Service Management Tools
# URL:         https://ulinux.org/
# Maintainer:  James Mills, prologic at shortcircuit dot net dot au

name=svc
version=1.0
release=1
source="$name service bare.sh"

build() {
  install -D -m 755 "$SRC"/$name "$PKG"/bin/$name
  install -D -m 755 "$SRC"/service "$PKG"/bin/service

  install -d "$PKG"/bin/svc.d/avail
  install -d "$PKG"/bin/svc.d/run
  install -D -m 755 "$SRC"/bare.sh "$PKG"/bin/svc.d/bare.sh
}
