--- Makefile.orig	2020-11-03 03:08:56.000000000 +1000
+++ Makefile	2020-11-08 22:02:12.000000000 +1000
@@ -102,7 +102,7 @@
 
 PROGS = tcc$(EXESUF)
 TCCLIBS = $(LIBTCCDEF) $(LIBTCC) $(LIBTCC1)
-TCCDOCS = tcc.1 tcc-doc.html tcc-doc.info
+TCCDOCS = tcc.1
 
 all: $(PROGS) $(TCCLIBS) $(TCCDOCS)
 
@@ -280,12 +280,6 @@
 
 # --------------------------------------------------------------------------
 # documentation and man page
-tcc-doc.html: tcc-doc.texi
-	$(call run-if,makeinfo,--no-split --html --number-sections -o $@ $<)
-
-tcc-doc.info: tcc-doc.texi
-	$(call run-if,makeinfo,$< || true)
-
 tcc.1 : tcc-doc.pod
 	$(call run-if,pod2man,--section=1 --center="Tiny C Compiler" \
 		--release="$(VERSION)" $< >$@ && rm -f $<)
@@ -318,8 +312,6 @@
 	$(call $(if $(findstring .so,$(LIBTCC)),IBw,IFw),$(LIBTCC),"$(libdir)")
 	$(call IF,$(TOPSRC)/libtcc.h,"$(includedir)")
 	$(call IFw,tcc.1,"$(mandir)/man1")
-	$(call IFw,tcc-doc.info,"$(infodir)")
-	$(call IFw,tcc-doc.html,"$(docdir)")
 ifneq "$(wildcard $(LIBTCC1_W))" ""
 	$(call IFw,$(TOPSRC)/win32/lib/*.def $(LIBTCC1_W),"$(tccdir)/win32/lib")
 	$(call IR,$(TOPSRC)/win32/include,"$(tccdir)/win32/include")
@@ -330,8 +322,7 @@
 uninstall-unx:
 	@rm -fv $(foreach P,$(PROGS) $(PROGS_CROSS),"$(bindir)/$P")
 	@rm -fv "$(libdir)/libtcc.a" "$(libdir)/libtcc.so" "$(libdir)/libtcc.dylib" "$(includedir)/libtcc.h"
-	@rm -fv "$(mandir)/man1/tcc.1" "$(infodir)/tcc-doc.info"
-	@rm -fv "$(docdir)/tcc-doc.html"
+	@rm -fv "$(mandir)/man1/tcc.1"
 	@rm -frv "$(tccdir)"
 
 # install progs & libs on windows
@@ -344,7 +335,6 @@
 	$(call IR,$(TOPSRC)/win32/examples,"$(tccdir)/examples")
 	$(call IF,$(TOPSRC)/tests/libtcc_test.c,"$(tccdir)/examples")
 	$(call IFw,$(TOPSRC)/libtcc.h $(subst .dll,.def,$(LIBTCC)),"$(libdir)")
-	$(call IFw,$(TOPSRC)/win32/tcc-win32.txt tcc-doc.html,"$(docdir)")
 ifneq "$(wildcard $(LIBTCC1_U))" ""
 	$(call IFw,$(LIBTCC1_U),"$(tccdir)/lib")
 	$(call IF,$(TOPSRC)/include/*.h $(TOPSRC)/tcclib.h,"$(tccdir)/lib/include")
@@ -370,14 +360,13 @@
 # cannot have both tags and TAGS on windows
 ETAGS : ; etags $(TAGFILES)
 
-# create release tarball from *current* git branch (including tcc-doc.html
+# create release tarball from *current* git branch
 # and converting two files to CRLF)
 TCC-VERSION = tcc-$(VERSION)
 TCC-VERSION = tinycc-mob-$(shell git rev-parse --short=7 HEAD)
-tar:    tcc-doc.html
+tar:
 	mkdir -p $(TCC-VERSION)
 	( cd $(TCC-VERSION) && git --git-dir ../.git checkout -f )
-	cp tcc-doc.html $(TCC-VERSION)
 	for f in tcc-win32.txt build-tcc.bat ; do \
 	    cat win32/$$f | sed 's,\(.*\),\1\r,g' > $(TCC-VERSION)/win32/$$f ; \
 	done
@@ -405,7 +394,7 @@
 	@$(MAKE) -s -C tests $@
 
 distclean: clean
-	@rm -fv config.h config.mak config.texi tcc.1 tcc-doc.info tcc-doc.html
+	@rm -fv config.h config.mak config.texi tcc.1
 
 .PHONY: all clean test tar tags ETAGS distclean install uninstall FORCE
 
