#!/bin/sh
# shellcheck disable=SC2034

# Description: Tiny C Compiler - C Scripting Everywhere
# URL:         https://repo.or.cz/tinycc.git/
# Maintainer:  Steffen Nurpmeso, steffen at sdaoden dot eu

name=tcc
version=20200416
gitver=8b69059f66c0ec402d9e81815978e7f70b7181d8
release=1
source="https://github.com/mirror/tinycc/archive/$gitver.zip
ar Makefile.patch"

build() {
  cd tinycc-$gitver || exit 1

  patch -i "$SRC"/Makefile.patch

  ./configure \
    --cc="${CC:-gcc}" \
    --config-musl \
    --prefix=/usr \
    --disable-static

  make
  make DESTDIR="$PKG" install

  # install ar wrapper
  install -D -m 755 "$SRC"/ar "$PKG"/usr/bin/ar
}
