#!/bin/sh
# shellcheck disable=SC2034

#!/bin/sh
# shellcheck disable=SC2034

# Description: CloudInit Tools
# URL:         https://ulinux.org/
# Maintainer:  James Mills, prologic at shortcircuit dot net dot au

name=cloudinit
version=1.0
release=1
source="$name $name.svc"
depends="svc"

build() {
  install -D -m 755 "$SRC"/$name "$PKG"/sbin/$name
}
