#!/bin/sh
# shellcheck disable=SC2034

# Description: Directory content manager
# URL:         http://www.kernel.org/pub/software/scm/git/docs
# Maintainer:  James Mills, prologic at shortcircuit dot net dot au

name=git
version=2.26.0
release=1
source="https://www.kernel.org/pub/software/scm/$name/$name-$version.tar.xz"
depends="zlib"

build() {
  cd $name-$version || exit

  ./configure \
    --prefix=/usr \
    --without-openssl \
    --without-expat \
    --without-iconv \
    --without-tcltk

  make -j "$(nproc)" \
    CFLAGS="$CFLAGS" \
    POFILES="" MOFILES="" NO_GETTEXT=1 \
    prefix=/usr \
    gitexecdir=/usr/lib/git-core \
    DESTDIR="$PKG" install
  rm -rf "$PKG"/usr/share/perl5
}
