#!/bin/sh
# shellcheck disable=SC2034

# Description: An SMTP client suitable for use with mutt etc.
# URL:         https://marlam.de/msmtp/
# Maintainer:  James Mills, prologic at shortcircuit dot net dot au

name=msmtp
version=1.8.7
release=1
source="https://marlam.de/msmtp/releases/$name-$version.tar.xz"

build() {
  cd $name-$version || exit 1

  ./configure \
    --prefix=/usr \
    --disable-nls \
    --with-tls=no \
    --without-libidn \
    --without-libsecret

  make -j "$(nproc)"
  make DESTDIR="$PKG" install
  rm -r "$PKG/usr/share/info"
}
