#!/bin/sh
# shellcheck disable=SC2034

# Description: uLinux Package Manager
# URL:         https://github.com/prologic/ulinux
# Maintainer:  James Mills, prologic at shortcircuit dot net dot au

name=pkg
version=0.0.12
release=1
source="pkg pkg.common pkg.conf ports repogen prtcreate"

build() {
  install -D -m 755 pkg "$PKG"/bin/pkg
  install -D -m 755 pkg.common "$PKG"/bin/pkg.common
  install -D -m 644 pkg.conf "$PKG"/etc/pkg.conf

  install -D -m 755 ports "$PKG"/bin/ports
  install -D -m 755 repogen "$PKG"/bin/repogen
  install -D -m 755 prtcreate "$PKG"/bin/prtcreate
}
