#!/bin/sh

_main() {
  cat > Pkgfile << EOF
#!/bin/sh
# shellcheck disable=SC2034

# Description: ...
# URL:         ...
# Maintainer:  ...

name=
version=
release=
source=""

build() {
}
EOF
}

if [ -n "$0" ] && [ x"$0" != x"-bash" ]; then
  _main "$@"
fi
