#!/bin/sh
# shellcheck disable=SC2034

# Description: strace Static Binary
# URL:         https://github.com/yunchih/static-binaries
# Maintainer:  James Mills, prologic at shortcircuit dot net dot au

name=strace-static
version=4.26
gitver=243e615f6326dfef570b1021af7b5da13539f242
release=2
source="https://github.com/yunchih/static-binaries/raw/$gitver/strace"

build() {
  install -D -m 755 "$SRC"/strace /usr/bin/strace
}
