#!/bin/sh
# shellcheck disable=SC2034

# Description: 80x86 assembler
# URL:         http://www.nasm.us/
# Maintainer:  James Mills, prologic at shortcircuit dot net dot au

name=nasm
version=2.14.02
release=1
source="http://www.nasm.us/pub/nasm/releasebuilds/$version/$name-$version.tar.xz"

build() {
  cd $name-$version || exit 1

  ./configure \
    --prefix=/usr

  make -j "$(nproc)"

  make DESTDIR=$PKG install

  rm -rf "$PKG"/usr/share
}
