#!/bin/sh

# shellcheck disable=SC1091
. /etc/rc.conf

printf "The system is coming up ...\n"

export PATH="/bin:/usr/bin:/sbin:/usr/sbin"

# Mount dev,proc,sys
mount -t devtmpfs none /dev
mount -t proc none /proc
mount -t sysfs none /sys
mkdir /dev/pts
mount -t devpts none /dev/pts

# Configure host name
HOSTNAME="${HOSTNAME:-localhost}"
hostname "$HOSTNAME"

# Configure networking
ip link set lo up
ip link set eth0 up

# Start syslogd (Logging)
syslogd

# Start udhcpc (DHCP)
udhcpc -f -p /var/run/udhcpc.pid > /var/log/udhcpc.log 2>&1 &

# Start rngd (TRNG)
if [ -c /dev/hwrng ]; then
  rngd -f -r /dev/hwrng -p /var/run/rngd.pid > /var/log/rngd.log 2>&1 &
fi

# Start dropbear (SSHD)
dropbear -B -R > /var/log/dropbear.log 2>&1

# Start crond
crond -b > /dev/null 2>&1

printf "\nBoot took %s seconds\n" "$(cut -d' ' -f1 /proc/uptime)"

# shell
while true; do
  setsid cttyhack /bin/sh &
  wait
done
