#!/bin/sh

if [ $# -ne 1 ]; then
  printf "usage: %s 0|6\n" "$(basename "$0")"
  exit 1
fi

case "$1" in
  0)
    /bin/kill -s USR1 1
    ;;
  6)
    /bin/kill -s INT 1
    ;;
  *)
    printf "error: invalid runlevel %s" "$1"
    exit 1
    ;;
esac
