#!/bin/sh
# shellcheck disable=SC2034

# Description: version of the TLS/crypto stack forked from OpenSSL
# URL:         http://www.libressl.org/
# Maintainer:  James Mills, prologic at shortcircuit dot net dot au

name=libressl
version=3.2.2
release=1
source="https://fossies.org/linux/misc/$name-$version.tar.gz"

build() {
  cd $name-$version || exit 1

  ./configure \
    --prefix=/usr \
    --with-openssldir=/etc/ssl

  make -j "$(nproc)"

  make DESTDIR="$PKG" install

  rm -rf "$PKG"/usr/lib/pkgconfig
  rm -rf "$PKG"/usr/share
}
