#!/bin/sh

# mount cgroup
(
  mount -t tmpfs -o uid=0,gid=0,mode=0755 cgroup /sys/fs/cgroup
  cd /sys/fs/cgroup || exit 1

  awk '!/^#/ { if ($4 == 1) print $1 }' /proc/cgroups | while IFS= read -r sys; do
    mkdir -p "$sys"
    if ! mountpoint -q "$sys"; then
      if ! mount -n -t cgroup -o "$sys" cgroup "$sys"; then
        rmdir "$sys" || true
      fi
    fi
  done
)
