---
name: Build
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Peepare
        run: |
          sudo apt-get install qemu
      - name: Build
        run: |
          make
